name: wildlog-relational-db

services:
  postgis:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wildlog-postgis
    platform: linux/amd64 # PostGIS does not support ARM, so platform must be specified oro it won't run on Apple Silicon
    environment:
      POSTGRES_DB: wildlog
      POSTGRES_USER: postgis
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - wildlog_postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgis"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  wildlog_postgres_data:
